name: styx_push_bridge_client
description: Flutter push notification client for Styx.
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  meta: ^1.16.0
  styx_transport: {path: ../transport}

dev_dependencies:
  dart_code_linter: ^4.1.6
  test: any
  very_good_analysis: any
