name: push_bridge_client
description: Flutter push notification client for Styx.
publish_to: none
resolution: workspace

environment:
  sdk: ^3.6.0

dev_dependencies:
  dart_code_linter: any
  test: any
  very_good_analysis: any
