name: styx_transport
description: Transport layer for Styx.
publish_to: none
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  cryptography: ^2.9.0
  enough_mail: ^2.1.7
  meta: ^1.16.0
  styx_crypto_core:
    path: ../crypto_core
  styx_ledger_engine:
    path: ../ledger_engine
  uuid: ^4.5.1

dev_dependencies:
  dart_code_linter: any
  test: any
  very_good_analysis: any
