name: styx
description: Public facade for the Styx library.
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  crypto: ^3.0.7
  meta: ^1.16.0
  styx_crypto_core: {path: ../crypto_core}
  styx_ledger_engine: {path: ../ledger_engine}
  styx_push_bridge_client: {path: ../push_bridge_client}
  styx_transport: {path: ../transport}

dev_dependencies:
  dart_code_linter: any
  test: any
  very_good_analysis: any
