/**
 * Cross-platform interoperability tests: verify JS against Dart test vectors.
 *
 * Loads dart_vectors.json generated by the Dart implementation and checks
 * that the JS implementation produces identical results after alignment fixes.
 */

import { describe, test, expect } from '@jest/globals';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

import * as ed from '@noble/ed25519';
import { StyxPublicKey, StyxPrivateKey, IdentityManager } from '../../src/crypto/identity.js';
import { Hasher } from '../../src/crypto/hasher.js';
import { Signer, Verifier } from '../../src/crypto/signer.js';
import { HybridLogicalClock } from '../../src/ledger/hlc.js';
import { VectorClock } from '../../src/ledger/vector-clock.js';
import { ShamirShare, ShamirReconstructor } from '../../src/crypto/shamir.js';
import { SessionVerifier } from '../../src/crypto/mnemonic.js';
import { Spake2Protocol } from '../../src/crypto/spake2.js';
import { QrPairingData } from '../../src/pairing/trust-store.js';
import { bytesToHex, hexToBytes, utf8Encode } from '../../src/utils.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const vectors = JSON.parse(readFileSync(join(__dirname, 'dart_vectors.json'), 'utf-8'));

function b64toBytes(b64) {
  return new Uint8Array(Buffer.from(b64, 'base64'));
}

describe('Dart ↔ JS Interoperability', () => {

  describe('Identity (Ed25519)', () => {
    test('derive same public key from private key', async () => {
      const privBytes = hexToBytes(vectors.identity.privateKeyHex);
      const pubBytes = await ed.getPublicKeyAsync(privBytes);
      expect(bytesToHex(pubBytes)).toBe(vectors.identity.publicKeyHex);
    });

    test('nodeId is first 8 hex chars of pubkey', () => {
      const nodeId = vectors.identity.publicKeyHex.substring(0, 8);
      expect(nodeId).toBe(vectors.identity.nodeId);
    });
  });

  describe('Ed25519 Signing', () => {
    test('verify Dart signature in JS', async () => {
      const payload = b64toBytes(vectors.signing.payload);
      const signature = hexToBytes(vectors.signing.signatureHex);
      const pubKey = new StyxPublicKey(hexToBytes(vectors.identity.publicKeyHex));
      const verifier = new Verifier();
      expect(await verifier.verify(payload, signature, pubKey)).toBe(true);
    });

    test('JS signature verifiable', async () => {
      const payload = b64toBytes(vectors.signing.payload);
      const privKey = new StyxPrivateKey(hexToBytes(vectors.identity.privateKeyHex));
      const pubKey = new StyxPublicKey(hexToBytes(vectors.identity.publicKeyHex));
      const signer = new Signer();
      const verifier = new Verifier();
      const sig = await signer.sign(payload, privKey);
      expect(await verifier.verify(payload, sig, pubKey)).toBe(true);
    });
  });

  describe('SHA-256 Hashing', () => {
    test('hash matches Dart', () => {
      const hasher = new Hasher();
      const result = bytesToHex(hasher.hash(b64toBytes(vectors.hashing.input)));
      expect(result).toBe(vectors.hashing.sha256);
    });

    test('chainHash matches Dart', () => {
      const hasher = new Hasher();
      const result = bytesToHex(hasher.chainHash(
        b64toBytes(vectors.hashing.chainHash.previousHash),
        b64toBytes(vectors.hashing.chainHash.payload),
      ));
      expect(result).toBe(vectors.hashing.chainHash.result);
    });

    test('chainHash genesis matches Dart', () => {
      const hasher = new Hasher();
      const result = bytesToHex(hasher.chainHash(
        null, b64toBytes(vectors.hashing.chainHashGenesis.payload),
      ));
      expect(result).toBe(vectors.hashing.chainHashGenesis.result);
    });

    test('compositeHash matches Dart', () => {
      const hasher = new Hasher();
      const segments = vectors.hashing.compositeHash.segments.map(b64toBytes);
      expect(bytesToHex(hasher.compositeHash(segments))).toBe(vectors.hashing.compositeHash.result);
    });
  });

  describe('HLC', () => {
    test('canonical format matches Dart', () => {
      const hlc = new HybridLogicalClock(
        new Date(vectors.hlc.timestamp),
        vectors.hlc.counter,
        vectors.hlc.nodeId,
      );
      expect(hlc.toCanonical()).toBe(vectors.hlc.canonical);
    });

    test('toBytes matches Dart', () => {
      const hlc = new HybridLogicalClock(
        new Date(vectors.hlc.timestamp),
        vectors.hlc.counter,
        vectors.hlc.nodeId,
      );
      expect(bytesToHex(hlc.toBytes())).toBe(vectors.hlc.bytesHex);
    });
  });

  describe('Vector Clock', () => {
    test('toBytes matches Dart', () => {
      const vc = new VectorClock(vectors.vectorClock.a, vectors.vectorClock.b);
      expect(bytesToHex(vc.toBytes())).toBe(vectors.vectorClock.bytesHex);
    });

    test('toJSON matches Dart', () => {
      const vc = new VectorClock(vectors.vectorClock.a, vectors.vectorClock.b);
      expect(vc.toJSON()).toEqual(vectors.vectorClock.json);
    });

    test('increment and merge match Dart', () => {
      const vc = new VectorClock(vectors.vectorClock.a, vectors.vectorClock.b);
      expect(vc.increment('A').toJSON()).toEqual(vectors.vectorClockOps.incrementA);
      expect(vc.increment('B').toJSON()).toEqual(vectors.vectorClockOps.incrementB);
      const other = VectorClock.fromJSON(vectors.vectorClockOps.mergeWith);
      expect(vc.merge(other).toJSON()).toEqual(vectors.vectorClockOps.mergeResult);
    });
  });

  describe('Event Hash', () => {
    test('event hash matches Dart', () => {
      const hasher = new Hasher();
      const segments = [
        utf8Encode(vectors.eventHash.previousHash),
        utf8Encode(vectors.eventHash.eventType),
        b64toBytes(vectors.eventHash.payload),
        b64toBytes(vectors.eventHash.hlcBytes),
      ];
      expect(bytesToHex(hasher.compositeHash(segments))).toBe(vectors.eventHash.result);
    });

    test('genesis event hash matches Dart', () => {
      const hasher = new Hasher();
      const segments = [
        utf8Encode(vectors.eventHashGenesis.eventType),
        b64toBytes(vectors.eventHashGenesis.payload),
        b64toBytes(vectors.eventHashGenesis.hlcBytes),
      ];
      expect(bytesToHex(hasher.compositeHash(segments))).toBe(vectors.eventHashGenesis.result);
    });
  });

  describe('Shamir', () => {
    test('reconstruct Dart shares produces original secret', () => {
      const shares = vectors.shamir.shares.map(s =>
        new ShamirShare(s.index, b64toBytes(s.data))
      );
      const reconstructor = new ShamirReconstructor();
      const result = reconstructor.reconstruct([shares[0], shares[2]]);
      expect(bytesToHex(result)).toBe(vectors.shamir.secretHex);
    });

    test('share serialization matches Dart format', () => {
      const share = new ShamirShare(
        vectors.shamir.shares[0].index,
        b64toBytes(vectors.shamir.shares[0].data),
      );
      expect(share.serialize()).toBe(vectors.shamir.shares[0].serialized);
    });

    test('deserialize Dart share format', () => {
      const deserialized = ShamirShare.deserialize(vectors.shamir.shares[1].serialized);
      expect(deserialized.index).toBe(vectors.shamir.shares[1].index);
      expect(bytesToHex(deserialized.data)).toBe(
        bytesToHex(b64toBytes(vectors.shamir.shares[1].data))
      );
    });
  });

  describe('QR Pairing', () => {
    test('parse Dart QR payload (JSON format)', () => {
      const data = QrPairingData.fromQrPayload(vectors.qrPairing.payload);
      expect(data.publicKey.toHex()).toBe(vectors.qrPairing.publicKeyHex);
      expect(data.relayHints).toEqual(vectors.qrPairing.relayHints);
    });

    test('JS QR payload roundtrip matches Dart format', () => {
      const pubKey = StyxPublicKey.fromHex(vectors.qrPairing.publicKeyHex);
      const nonce = b64toBytes(vectors.qrPairing.nonce);
      const data = new QrPairingData(pubKey, nonce, vectors.qrPairing.relayHints);
      const payload = data.toQrPayload();
      // Should be valid JSON
      const parsed = JSON.parse(payload);
      expect(parsed.pk).toBe(vectors.qrPairing.publicKeyHex);
      expect(parsed.r).toEqual(vectors.qrPairing.relayHints);
    });
  });

  describe('Double Check Code', () => {
    test('generates same code as Dart', () => {
      const sessionKey = hexToBytes(vectors.doubleCheck.sessionKeyHex);
      const verifier = new SessionVerifier();
      expect(verifier.generateDoubleCheckCode(sessionKey)).toBe(vectors.doubleCheck.code);
    });
  });

  describe('SPAKE2 password', () => {
    test('mnemonicToPassword matches Dart (raw UTF-8)', () => {
      const protocol = new Spake2Protocol();
      const password = protocol.mnemonicToPassword(vectors.spake2.mnemonic);
      expect(bytesToHex(password)).toBe(vectors.spake2.passwordHex);
    });
  });
});
